apiVersion: v2
appVersion: 2.31.5
dependencies:
- condition: mysql.enabled
  name: mysql
  repository: '@bitnami'
  version: ~9.1.7
- condition: postgresql.enabled
  name: postgresql
  repository: '@bitnami'
  version: ~11.6.5
- alias: postgresqlha
  condition: postgresqlha.enabled
  name: postgresql-ha
  repository: '@bitnami'
  version: ~9.4.0
- condition: rabbitmq.enabled
  name: rabbitmq
  repository: '@bitnami'
  version: ~11.2.0
- condition: redis.enabled
  name: redis
  repository: '@bitnami'
  version: ~16.12.0
description: A Helm chart for Kubernetes to install DefectDojo
icon: https://www.defectdojo.org/img/favicon.ico
maintainers:
- email: defectdojo-project@owasp.org
  name: madchap
  url: https://github.com/DefectDojo/django-DefectDojo
name: defectdojo
version: 1.6.113
