istiod:
  meshConfig:
    rootNamespace: "istio-system"
    accessLogEncoding: "JSON"
    accessLogFile: "/dev/stdout"
    trustDomain: "cluster.local"

istio-ingress-internal:
  meshConfig:
    trustDomain: "cluster.local"
  gateways:
    istio-ingressgateway:
      name: ingressgateway-internal
      labels:
        app: ingressgateway-internal
        istio: ingressgateway-internal
      type: "LoadBalancer"
      ports:
        - name: status-port
          port: 15021
          protocol: TCP
        - name: http2
          port: 80
          protocol: TCP
          targetPort: 8080
        - name: https
          port: 443
          protocol: TCP
          targetPort: 8443
        - name: prometheus
          port: 9090
          protocol: TCP
          targetPort: 9090
      selector:
        app: ingressgateway-external
        istio: ingressgateway-external


    