apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: argocd
spec:
  destination:
    namespace: dd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: dd
    repoURL: https://github.com/ra1nst0rm3d/argo_test
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        istio-injection: enabled