apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argocd
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: istio
    repoURL: https://github.com/ra1nst0rm3d/argo_test
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    ignoreDifferences:
      - group: admissionregistration.k8s.io
        kind: MutatingWebhookConfiguration
        jsonPointers:
          - /webhooks/0/clientConfig/caBundle
          - /webhooks/1/clientConfig/caBundle
          - /webhooks/2/clientConfig/caBundle
          - /webhooks/3/clientConfig/caBundle
      - group: admissionregistration.k8s.io
        kind: ValidatingWebhookConfiguration
        jsonPointers:
          - /webhooks/0/clientConfig/caBundle
          - /webhooks/0/failurePolicy
          - /webhooks/1/clientConfig/caBundle
          - /webhooks/1/failurePolicy
